# try:
# except:
# finally:
# else 

# def divide(a,b):
#     if b==0:
#         return "cannot divide by zero"
#     else:
#         return a/b

# print(divide(10,0))
# try catch finally



try: # Code that may raise an exception
    result = 3 / 222222222224242422242424224224276565465464646546464646464646464664646464464646464646464646464646464242422424242424242424242424242424424242424424242424240
    print(result)
except Exception as e:
    print(f"An error occurred: {e}")
else: 
    print("execute when No error occurred")
finally:
    print("This code will always run")

